steps:
# Build using Node.js builder
- name: "gcr.io/cloud-builders/npm"
  args: ["install"]

- name: "gcr.io/cloud-builders/npm"
  args: ["run", "build"]

# Create a Docker image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/thefmsmkt-pos:$COMMIT_SHA", "-f", "Dockerfile.simple", "."]

# Push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/thefmsmkt-pos:$COMMIT_SHA"]

# Deploy container image to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
  - "run"
  - "deploy"
  - "thefmsmkt-pos"
  - "--image=gcr.io/$PROJECT_ID/thefmsmkt-pos:$COMMIT_SHA"
  - "--region=us-central1"
  - "--platform=managed"
  - "--allow-unauthenticated"

images:
- "gcr.io/$PROJECT_ID/thefmsmkt-pos:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
