steps:
# Build using buildpacks with the exact command
- name: "gcr.io/k8s-skaffold/pack"
  entrypoint: "pack"
  args:
  - "build"
  - "gcr.io/ai-qr-genius/github.com/thefamousmarket/thefmsmkt_-pos-interaktif-dengan-gemini:$COMMIT_SHA"
  - "--builder=gcr.io/buildpacks/builder"
  - "--publish"

# Deploy to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
  - "run"
  - "deploy"
  - "thefmsmkt-pos"
  - "--image=gcr.io/ai-qr-genius/github.com/thefamousmarket/thefmsmkt_-pos-interaktif-dengan-gemini:$COMMIT_SHA"
  - "--region=us-central1"
  - "--platform=managed"
  - "--allow-unauthenticated"

images:
- "gcr.io/ai-qr-genius/github.com/thefamousmarket/thefmsmkt_-pos-interaktif-dengan-gemini:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
  env:
  - "COMMIT_SHA=$COMMIT_SHA"
  - "PROJECT_ID=$PROJECT_ID"
