-- SQL migration for EInvoices table (for SQLite/MySQL/Postgres)
CREATE TABLE IF NOT EXISTS EInvoices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invoice_number VARCHAR(64) UNIQUE NOT NULL,
  invoice_date DATETIME NOT NULL,
  supplier_name VARCHAR(255) NOT NULL,
  supplier_brn VARCHAR(64) NOT NULL,
  supplier_sst_reg_no VARCHAR(64),
  supplier_address TEXT,
  supplier_contact VARCHAR(128),
  customer_name VARCHAR(255) NOT NULL,
  customer_brn VARCHAR(64),
  customer_sst_reg_no VARCHAR(64),
  customer_address TEXT,
  customer_contact VARCHAR(128),
  line_items TEXT NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL,
  total_tax_amount DECIMAL(12,2) NOT NULL,
  total_amount_due DECIMAL(12,2) NOT NULL,
  payment_mode VARCHAR(64) NOT NULL,
  currency_code VARCHAR(8) NOT NULL,
  irbm_unique_identifier VARCHAR(128),
  digital_signature TEXT,
  qr_code_data TEXT,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL,
  submission_response TEXT
);
